# coding: utf-8

# flake8: noqa

"""
    EO Data Store API

    EO Data Store Manager indexing all data hosted on a set of storages  # noqa: E501

    OpenAPI spec version: draft-3
    Contact: christophe.noel@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from datastore.api.datasets_api import DatasetsApi
from datastore.api.groups_api import GroupsApi
# import ApiClient
from datastore.api_client import ApiClient
from datastore.configuration import Configuration
# import models into sdk package
from datastore.models.dataset import Dataset
from datastore.models.dataset_change import DatasetChange
from datastore.models.dataset_description import DatasetDescription
from datastore.models.dataset_info_details import DatasetInfoDetails
from datastore.models.generic_data_properties import GenericDataProperties
from datastore.models.group import Group
from datastore.models.product_properties import ProductProperties
